accelerate launch src/run_sft_qlora.py \
    --model_checkpoint "GoToCompany/gemma2-9b-cpt-sahabatai-v1-base" \
    --train_file public_data_test/track_a/train/sun.csv \
    --dev_file public_data_test/track_a/dev/sun.csv \
    --max_length 128 \
    --batch_size 32 \
    --learning_rate 2e-4 \
    --max_grad_norm 1.0 \
    --warmup_steps 20 \
    --num_epochs 5 \
    --gradient_checkpointing \
    --apply_liger_kernel_to_gemma2